export const enum PROVIDER {
  AUTH_SERVICE = 'AUTH_SERVICE',
  KAKAO_SERVICE = 'KAKAO_SERVICE',

  USER_GUARD = 'USER_GUARD',
  REISSUE_GUARD = 'REISSUE_GUARD',

  USER_REPOSITORY = 'USER_REPOSITORY',
  KAKAO_ACCOUNT_REPOSITORY = 'KAKAO_ACCOUNT_REPOSITORY',

  DATABASE_PROVIDER = 'DATABASE_PROVIDER',
}
