export const enum PROVIDER {
  AUTH_SERVICE = 'AUTH_SERVICE',
  KAKAO_SERVICE = 'KAKAO_SERVICE',

  AUTH_GUARD = 'AUTH_GUARD',
  REISSUE_GUARD = 'REISSUE_GUARD',

  USER_REPOSITORY = 'USER_REPOSITORY',
  KAKAO_ACCOUNT_REPOSITORY = 'KAKAO_ACCOUNT_REPOSITORY',
}
