name: Deploy to cloudtype
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: apis/uniem
          stage: main
          yaml: >
            name: uniem-be

            app: node@16

            options:
              env:
                - name: NODE_ENV
                  value: production
                - name: REDIRECT_URI
                  value: https://port-0-uniem-be-17xqnr2llgw1m3ja.sel3.cloudtype.app/auth/kakao/redirect
                - name: KAKAO_REST_API_KEY
                  value: a01b9c2e086effca22185702d4e04fe4
              ports: "4000"
              build: yarn run build
              start: yarn run start:prod
              install: yarn install
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
